#!/bin/sh
#
# This script opens a tab in the browser with the editor in the current directory.
# The server must have been started before.
#
# This is for use on windows msys environment.

# change /c/... to /c:/...
rootDir=`echo $PWD | sed 's/\(..\)/\1:/'`
start "http://127.0.0.1:1978${rootDir}" 
